stages:
  - build
  - deploy

build:
  image: maven:3-jdk-11
  stage: build
  script:
    - "mvn clean install -f Backend/pom.xml -DoutputDirectory=/"

  artifacts:
    paths:
      - Backend/target/carrental-0.0.1-SNAPSHOT.jar
      - Procfile

staging:
  image: ruby:2.3
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=carrental-dev --api-key=$HEROKU_API_KEY
  - echo "Deployed to Staging Server https://carrental-dev.herokuapp.com/"
  environment:
    name: staging
  only:
    - dev-backend
