stages:
  - build
  - deploy

cache:
  paths:
    - .m2/repository

build:
  image: maven:3-jdk-11
  stage: build
  script:
    - cd Backend
    - "mvn clean install"
    - cd ..

  artifacts:
    paths:
      - Backend/target/carrental-0.0.1-SNAPSHOT.jar
      - Procfile

staging:
  stage: deploy
  script:
    - ls
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/carrental-dev.git
    - git push -f heroku HEAD:refs/heads/master
    - echo "Deployed to Staging Server https://carrental-dev.herokuapp.com/"
  environment:
    name: staging
  only:
    - dev-backend
