spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrental
    username: carrental
    password: Zaq12345@!
  mail:
    host: localhost
    port: 25
    username: test
    password: test
