spring:
  datasource:
    url: jdbc:postgresql://ec2-54-157-78-113.compute-1.amazonaws.com:5432/d5566v6jq399b8?currentSchema=carrental
    username: ruwlfmqrxokodk
    password: a31216198c6382796d3c32f9de63f2dd82632f6d5a43eeee7fea9e3d10360722
    platform: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: carrental.wsiz@gmail.com
    password: Carrental.wsiz1
    properties:
      smtp:
        auth: true
      starttls:
        enable: true